#!/usr/bin/env python
import argparse
import arxiv_library.pipeline
parser = argparse.ArgumentParser()
parser.add_argument(
        'tar_path',
        help='The directory where the tar files are located',
        type=str)
parser.add_argument(
    'json_path',
    help='The directory where the resulting json files will be stored',
    type=str)
parser.add_argument(
    '-fulltext',
    help='Iff this flag is set, the paper will be stored in the paper dict with key "paper"',
    action='store_true')
args = parser.parse_args()
arxiv_library.pipeline.pipeline(args.tar_path, args.json_path, args.fulltext)
